url: http://www.rszx.org

title: 荣钜机械

keywords: 

description: 

address: 广东省佛山市南海区里水镇水口村环村路13号

tel: 0757-85618418

phone: 13535723990

fax: 0757-85683980

email: guojrong@163.com

qq: 

weixin: 13535723990

exclude:
  - README.md
  - style.css
